##
## EPITECH PROJECT, 2021
## solo stumper
## File description:
## Makefile
##


SRC =	func.c \
		bonus.c \

NAME = bonus

all: $(NAME)

$(NAME):
	gcc -O3 $(SRC) -o $(NAME)

clean:
	rm -f $(NAME)

fclean:	clean

re:	fclean all
